amrayn/easyloggingpp

- src/easylogging++.h
When ELPP_UNICODE is defined, *ptr is wchar_t, but stringstream::operator<< sees it as a long, which converts it to a number. So we have to cast it to a char to ensure we get a character.
> Fix to custom datetime format in Unicode mode

- doc/RELEASE-NOTES-v9.90
- samples/STL/custom-format-spec.cpp
- src/easylogging++.h
This allows the custom formatter to customize the formatting per message based on the message context (and by extension its logger).
> Pass LogMessage to custom formatter function

- README.md
- samples/Qt/basic/test_conf.conf
- samples/STL/logrotate.conf
- samples/console.conf
- samples/default-logger.conf
- samples/file.conf
- src/easylogging++.cc
As previously discussed, this patch will replace `MILLISECONDS_WIDTH` with `SUBSECOND_PRECISION`, but continue to recognize `MILLISECONDS_WIDTH`.
This patch has *not* changed the enumerator `ConfigurationType::MillisecondsWidth`, nor the class `MillisecondsWidth`. A related issue is that while the documentation talks about `SUBSECOND_PRECISION` now, `ConfigurationTypeHelper::convertToString` still returns `MILLISECONDS_WIDTH`. I would like to change this along with the enumerator/class change, if you are satisfied with the current changes.
The code can be further simplified if the lower-case form is not necessary. It seems the current code always converts the conf strings to upper case before invoking `ConfigurationTypeHelper::convertFromString`, and the function does not process …
> Subsecond Precision

- doc/RELEASE-NOTES-v9.90
- src/easylogging++.h
1. Set ELPP_CXX11 only when the compiler’s C++ standard is C++11 or later (esp. GCC and Clang).
2. Do not use Clang version, as it is not reliable.
3. Detect and use std::thread when Clang can find the header file (this also fixes the problem that `%thread' does not output anything in Clang prior to this change).
4. Prompt the users they may forget to specify `-std=c++11' if C++11 support is not detected.
> Improve detection of C++11 support.

- README.md
- samples/async/prog.cpp
- src/easylogging++.cc
- src/easylogging++.h
- test/enum-helper-test.h
- test/log-format-resolution-test.h
- test/test.h
1. Use the new SubsecondPrecision enumerator.
2. Rename class MillisecondsWidth to SubsecondPrecision.
3. Add and use TypedConfigurations::subsecondPrecision.
4. Rename kDefaultMillisecondsWidth to kDefaultSubsecondPrecision.
5. Rename TypedConfigurations::m_millisecondsWidthMap to TypedConfigurations::m_subsecondPrecisionMap.
6. Update comments.
7. Fix DateTime::getTimeDifference.
8. Use the usual abbreviation of microseconds.
> Replace remaining MillisecondsWidth and fix time issues.

- src/easylogging++.h
When using clang and libstdc++, libstdc++ must be new enough.
Also enable std::thread when C++11 is detected and the compiler is neither MinGW GCC nor Clang.
> Enable std::thread selectively.

- test/build_and_run.sh
- test/test.h
1. Make gtest work when it is not installed to system directories, by suppressing warnings emitted from gtest.
2. Clean up the build script.
> Fix gtest problems

- src/easylogging++.h
Current GCC warns about unused constants if -Wunused-variable is used (explicitly or implicitly). Add pragmas to disable them.
> Disable GCC warnings about unused constants.

- src/easylogging++.h
The backslash behind INITIALIZE_NULL_EASYLOGGINGPP macro should have one space at least.
> Fix VisualStudio 2015 compile error.

- README.md
- src/easylogging++.h
They allow disabling definitions of *CHECK* and *DEBUG*
macros, respectively.
> Add ELPP_DISABLE_CHECK_MACROS and ELPP_DISABLE_DEBUG_MACROS

- src/easylogging++.cc
I use "warnings as errors" in my project in MSVC 2015. I got a few issues when I added in easylogging++ so fixed them here.
> Fixes for /W4 level warnings generated in MSVC compile

- CMakeLists.txt
- src/easylogging++.cc
- src/easylogging++.h
This patch adds the ability to build easyloggingpp as a static library and to log in UTC time. Totally optional, nothing changes if the user chooses not to build the static library.
> Add options to build as a static library and log in UTC time

- src/easylogging++.cc
In case __FILE__ macro expands to absolute or relative paths
the vmodule wildcard check fails if modules are only specified
with base filenames.
demo.cc:
```C++
#include "easylogging++.h"
#include "header.h"
INITIALIZE_EASYLOGGINGPP
int main(int argc, char* argv[]) {
START_EASYLOGGINGPP(argc, argv);
el::Loggers::removeFlag(el::LoggingFlag::AllowVerboseIfModuleNotSpecified);
VLOG(1) << "demo: verbose 1 logging";
VLOG(2) << "demo: verbose 2 logging";
foo1();
foo2();
return 0;
}
```
header.h:
```C++
#pragma once
#include "easylogging++.h"
static inline void foo1() {
VLOG(1) << "fooo verbosity 1";
}
static inline void foo2() {
VLOG(2) << "fooo verbosity 2";
}
```
compile with: ``g++ demo.cc easylogging++.cc -o test -std=c++11 ``
example call that previously did not output anything: ``./test …
> use base filename for vmodule wildcard matches

- CMakeLists.txt
I have some source files that use easyloggingpp (linking against the static library), and these files are later used to create a shared lib (.so).
Without this patch, I got linking error because the code is not position independant.
This patch fixes this issue.
> generate PIC code for the library

- src/easylogging++.h
Hi,
This PR follows #620 and https://github.com/amrayn/easyloggingpp/commit/b96d4895fb3dee44be16d5ab9dd98fcfee49bd30, and fixes the following warning :
```
‘el::base::consts::kSysLogLoggerId’ defined but not used [-Wunused-variable]
783 static const char* kSysLogLoggerId                         =      "syslog";
```
It then closes #742.
Thank you 👍
> kSysLogLoggerId defined but not used

- CMakeLists.txt
- src/easylogging++.cc
- src/easylogging++.h
MUSL libc does not natively have libexecinfo. Adding this change,
make execinfo optional. Also made a PR https://github.com/MisterTea/EternalTerminal/pull/269 that uses this as part of their dependencies. So this would make a complete set if both PRs get merged.
Signed-off-by: Nathan Owens <ndowens04@gmail.com>
> Add if defined EXECINFO

- src/easylogging++.cc
This is the only warning, preventing from compiling with GCC strict compilation flags.
> Comment unused variable

- src/easylogging++.cc
- src/easylogging++.h
On the UGW platform, a SIGSEGV event is sent to a prplmesh application
that utilizes the easylogging++ library. The event is sent due to an
access attempt to a released memory. The released memory is a pointer
to the "LogStreamsReferenceMap m_logStreamsReference" which is defined
statically in RegisteredLoggers class.
The RegisteredLoggers object is released in UGW before the release of
other Class objects that make use of the pointer, and thus - the pointer is accessed
after the map is already released.
The issue may be seen in other platforms and is dependent on the difference in object release order.
After this change, the map is defined as a shared-pointer in the RegisteredLoggers class
and is set to a shared-pointer of type LogStreamsReferenceMap in the RegisteredLoggers CTOR. Even …
> bug - access attempt to released memory

- README.md
The README has a minor error regading the function signature to be used by ```CustomFormatSpecifier```, it seems that the function should have ```const el::LogMessage*``` as a parameter.
Just a minor README update.
> Fixing Readme for the right CustomFormatSpecifier signature

- src/easylogging++.cc
Fixes a crash in the tests
- [ x] Merged in the latest upstream changes
- [ x] [Run the tests](README.md#install-optional)
> Fix using invalid dateIndex (std::string::npos)
